### ISSUE TITLE
SWD blind

### ISSUE THREAD

**Issue by debugger12313** [gamefreedomgit/Frostmourne#1197]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Shadow word death (SWD) doesnt break blind if you have power word: shield active.

How it should work: 
Blind should break once u get the back damage from shadow word: death even with power word: shield and divine aegis active.

**Database links:**

**Comment by WhitemaneIsa** [comment]
Any Source Info?

**Comment by debugger12313** [comment]
This is a pretty low quality video but at the end u can see repentance getting SWD'd even though the priest got power word: shield up. Repentance and blind both break on damage and here you can see the backlash from SWD getting absorbed. 
https://www.youtube.com/watch?v=5loNlXzBiq0&ab_channel=DanRocal39

**Comment by debugger12313** [comment]
I can remember clearly that blind would break from SWD with pws up but "trust me bro" doesnt quite cut it. What other evidence do you need? This is pretty gamebreaking.

**Comment by UltraNix** [comment]
Fixed.

**Comment by debugger12313** [comment]
Its not fixed. Tried SWD with pws up on a scatter shot and it didnt break.
