### ISSUE TITLE
Dancing rune weapon few bugs

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1459]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. DRW autoattacks are doing less damage than it should. (same weapon, around the same attack power)
wotlk classic PTR https://www.youtube.com/watch?v=wNgnm1YnALs doing around 1400 autoattack without crit
whitemane PTR https://www.youtube.com/watch?v=EyZmMdXH2LQ doing around 800 autoattack without crit (also shouldn't parry on first hit as DRW should spawn on the back of the enemy).
Take in mind that PTR classic video is versus grandmaster dummy and whitemane ptr is versus heroic training dummy so difference is even more than 600 damage, should be about 700-800 per one normal hit.
3.  You can't spread out DRW diseases to other targets.
4. If you have additional targets near main target and you press pestilence while DRW is active you should get DRW diseases on main target as seen here https://youtu.be/3m3CaB2k-tM?t=27
5. There is a visual bug with target debuff if you kill target or a player and you swap on other target DRW debuff is always set on 17 seconds - this is not so important.

**How to reproduce:**

Use DRW and test.

**How it should work:**
1. DRW autoattacks should do more damage
2. You should be able to spread DRW diseases to other targets
3. Pressing pestilence on DRW gives double diseases on main target if there is other target
4. No visual bug with timer debuff on enemy
**Database links:**

**Comment by danniellos94** [comment]
Found new bug, if you are using heart strike while DRW is active you will hit up to 6 targets (2 yours and 4 from DRW) it should be only 4 targets (2 from you and 2 from DRW).

**Comment by danniellos94** [comment]
@UltraNix possible too fix soon?

**Comment by Piootrek** [comment]
All issues have been fixed.

**Comment by Sylanha** [comment]
Is this on the live server? Because for me it doesn't work. And also please try to do it from the center dummy.

**Comment by danniellos94** [comment]
@Piootrek Are all the fixes up on PTR ? Because it seems that 
1. is semi working still missing damage to what I linked, I'm getting now 1k autottack damage instead of 800, and should be around 1400 according to vid.
2. this is not working - you should be able to spread DRW diseases to other targets by other way pressing 2 times pestilence on DRW (while having your own diseases on main target) or casting icy touch + plague strike and then pestilence on DRW.
3. is working
4. is working

**Comment by Piootrek** [comment]
Diseases spreading is fixed, will be live on the server after next update. I will check further melee damage.

**Comment by danniellos94** [comment]
All issues have been fixed,, with melee damage we will stay with lower damage but mathematical correct.
