### ISSUE TITLE
[PoW] Some Items are missing Stats Completely

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Some preset items are missing stats completely. I suspect it may have something to do with them never having been implemented on bl!zz og wrath?

What I have tested:

Savage Gladiator's Bonegrinder  https://www.wowhead.com/wotlk/item=42295/savage-gladiators-bonegrinder#comments
This one provides 0 AP - it's basically fancy, but completely useless in its current form.
![image](https://github.com/user-attachments/assets/78c87cf2-8521-4680-981e-f494c257c18c)
![image](https://github.com/user-attachments/assets/db6a442e-3630-45c6-ad2f-731e87700765)

Savage Gladiator's Libram of Justice https://www.wowhead.com/wotlk/item=42612/savage-gladiators-libram-of-justice
Gives nothing at all -> useless
![image](https://github.com/user-attachments/assets/9045ca1d-1df5-4b29-953f-83fb050c4d06)

Gavel  https://www.wowhead.com/wotlk/item=42344/savage-gladiators-gavel
No SP at all, no MP5 at all -> basically useless
![image](https://github.com/user-attachments/assets/5678b7f3-b0e6-4762-b393-788ab15d2fed)

Redoubt https://www.wowhead.com/wotlk/item=42568/savage-gladiators-redoubt
No SP, No MP5 at all -> basically useless
![image](https://github.com/user-attachments/assets/ffcd6519-54cf-4643-a0a6-8836ebea5168)

If it is client side issue, I recommend swapping Savage Glad weapons to Hateful ones, as I have added them on the PTR and they have their missing stats.

Also Adding Hateful weapons for honor to a vendor would be nice so the upgrading can be more incremental.

Comparison: https://www.wowhead.com/wotlk/item=42569/hateful-gladiators-redoubt    https://www.wowhead.com/wotlk/item=42568/savage-gladiators-redoubt

![image](https://github.com/user-attachments/assets/9854216d-4a99-459a-af8c-98a67ce2449f)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Should be fixed.

**Comment by haephaistoss** [comment]
@UltraNix 
It's missing other stats now.
![image](https://github.com/user-attachments/assets/1260f292-8555-46bd-b94b-3ca2c88f9926)

Shield is still the same:

![image](https://github.com/user-attachments/assets/fdfd0fef-84c8-4cca-8236-f8a6ceb874a4)

**Comment by UltraNix** [comment]
Will be fixed soon.
