### ISSUE TITLE
Missing item from transmog list

### ISSUE THREAD

**Issue by andjsavin** [gamefreedomgit/Frostmourne#1624]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I am mage (nickname Mint) and have Warpthread west in my inventory.
![image](https://github.com/user-attachments/assets/523c975c-8e72-4816-a3b7-10d2ce4ade0f)
But it is missing from transmog list. It has the same model as Silver-Thread Armor, but it is missing too.

**How to reproduce:**

**How it should work:**
It should be available in transmog list for mage.

**Database links:**
https://www.wowhead.com/wotlk/item=30518/warpthread-vest
https://www.wowhead.com/wotlk/item=7110/silver-thread-armor

**Comment by andjsavin** [comment]
Update, farmed Silver-Thread Armor and it is also not in the list, despite it told me that it was added to collection
![image](https://github.com/user-attachments/assets/dc092f06-9918-4dee-b97e-f18b5efbff2b)

**Comment by kingreda11** [comment]
should we have whitemane+ to get xmog list and things?

**Comment by andjsavin** [comment]
No, we can do xmog like in cata now without whitemane+

**Comment by Piootrek** [comment]
> @Piootrek can you change these too? Currently they don't work like that, Main hand only works for Main Hand and Off Hand only works for Off Hand type which is correct but One Hand Type cannot be used for Main or Off Hand type and Guns Bows and Crossbows the Crossbow to Bow part doesn't work
> 
> Weapons must be the same weapon type (exceptions: Guns, Crossbows, or Bows) Guns, Crossbows, and Bows can be used to transmogrify Guns, Crossbows, or Bows
> 
> Main hand weapons can only be used to transmogrify Main hand weapons Off-hand weapons can only be used to transmogrify Off-hand weapons One handed weapons can be used to transmogrify a Main hand or Off-hand weapon

Done

**Comment by andjsavin** [comment]
Still don't have it in the list. No Warpthread Vest, No Silver-Thread Armor
![image](https://github.com/user-attachments/assets/4838f053-48b1-492e-9084-5e0e916716df)

**Comment by Piootrek** [comment]
Server wasn't updated yet. Wait for update (I will close this issue then)

**Comment by WhitemaneChronus** [comment]
@Piootrek Seems player equipping a one-handed weapon [hailstorm](https://www.wowhead.com/wotlk/item=40491/hailstorm) can only see options for one-handed; as an example they are unable to transmog it to [the willbreaker](https://www.wowhead.com/wotlk/item=27512/the-willbreaker)

![image](https://github.com/user-attachments/assets/60f98350-78cc-45c4-9c74-26f8e850f64a)
