### ISSUE TITLE
Releasing spirit inside Blackrock mountain causes teleport to the Barrens graveyard

### ISSUE THREAD

**Issue by Whynoth** [gamefreedomgit/Frostmourne#1751]
![Barrens_express](https://github.com/user-attachments/assets/0aca9651-652a-45c0-b2e6-e0ae87e292a2)

**Description**
Releasing spirit after dying in certain places inside the Blackrock mountain causes the player to be teleported to the cemetary south of Crossroads, making the corpse run to get the Shadowforge key quest unlikely.

**How to reproduce:**
1. Be horde, [havent tested with alliance...]
2. Go to blackrock,
3. Die by swimming in the lava ***OR*** by yeeting yourself off the BRS terrace,
4. Release spirit.

**How it should work:**
Your ghost should spawn at the Thorium's Point graveyard

**Database links:**
https://www.wowhead.com/wotlk/quest=3801/dark-iron-legacy

**Comment by WhitemaneChronus** [comment]
while i have seen several reports of this issue, here's an example that alliance player gets teleported to westfall after dying to lava pool in blackrock mountain.
![image](https://github.com/user-attachments/assets/6d571749-f95b-40ad-9ad0-69fd72722745)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes lives.

**Comment by scrublama** [comment]
> Fixed, I will close this issue once the fix comes lives.

@Piootrek https://clips.twitch.tv/create/CrazySpineyFlamingoCorgiDerp-saoXnYdU_zBeUHzW

**Comment by Greywolf59** [comment]
Still not fixed, can confirm. Got teleported to the Barrens.
