### ISSUE TITLE
[Quest] Stitches

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1887]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Stitches is not being spawned upon accepting quest [Translation to Ello].

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/npc=412/stitches
https://www.wowhead.com/classic/npc=412/stitches#comments:id=2892803
https://www.wowhead.com/wotlk/quest=252/translation-to-ello

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Chaos-within** [comment]
Stitches is still not working, yet to be seen on live realm after doing quests.

**Comment by Piootrek** [comment]
My bad. Fixed it and I will close this issue once the fix comes live.

**Comment by Chaos-within** [comment]
Still not working

**Comment by Chaos-within** [comment]
He is despawning randomly, before he even begins his assault on the town. I don't think he should ever despawn, and definitely not before reaching the town

**Comment by Piootrek** [comment]
Changed despawn time to 1h.
