### ISSUE TITLE
[Dungeon] [NPC] Nexus Trash – Missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2121]
[Crazed Mana-Surge](https://www.wowhead.com/npc=26737/crazed-mana-surge) is or was missing [Arcane Nova](https://www.wowhead.com/spell=47696/arcane-nova) ability.
https://wowpedia.fandom.com/wiki/Crazed_Mana-Surge

[Crystalline Tender](https://www.wowhead.com/wotlk/npc=28231/crystalline-tender) is missing [Tranquility](https://www.wowhead.com/spell=51972/tranquility). [Toughen Hide](https://www.wowhead.com/spell=50994/toughen-hide) usage should also be checked.
https://wowpedia.fandom.com/wiki/Crystalline_Tender

[Mage Slayer](https://www.wowhead.com/wotlk/npc=26730/mage-slayer#abilities;mode:normal) needs to be checked for abilities. tested on warrior, but never seen it happenign on my mage either. [Draw Magic](https://www.wowhead.com/wotlk/spell=50131/draw-magic) seems to be missing. [Spell Lock](https://www.wowhead.com/wotlk/spell=30849/spell-lock) needs to be checked too.
https://wowpedia.fandom.com/wiki/Mage_Slayer?so=search

[Mage Hunter Ascendant](https://www.wowhead.com/wotlk/npc=26727/mage-hunter-ascendant) is missing Spellstealable [Aura of Arcane Haste](https://www.wowhead.com/wotlk/spell=50182/aura-of-arcane-haste).
Mage Hunter Ascendants are only meleeing. Full list of missing abilities: https://wowpedia.fandom.com/wiki/Mage_Hunter_Ascendant?so=search and https://wotlk-twinhead.twinstar.cz/?npc=26727#abilities

[Horde Ranger ](https://www.wowhead.com/wotlk/npc=26801/horde-ranger)(and probably Alli too) does nto sue bo at all, instead runs after the target, sword swinging. Missing all the abilities listed here: https://wowpedia.fandom.com/wiki/Horde_Ranger?so=search and https://wotlk-twinhead.twinstar.cz/?npc=26801#abilities

[Horde Berserker](https://www.wowhead.com/wotlk/npc=26799/horde-berserker#drops;mode:normal) (Alli version probably too) seems to be also missing all the abilities. List: https://wowpedia.fandom.com/wiki/Horde_Berserker_(Nexus)?so=search#Abilities

https://www.youtube.com/watch?v=c-4nOs5lh8w&ab_channel=wowZyack

Seeing as the list is pretty decent, all abilities of all Nexus mobs should be rechecked.

**Comment by Afgann** [comment]
fixed

**Comment by Greywolf59** [comment]
Looks like it is working, haven't checked all spells. However I have noticed [Aura of Arcane Haste](https://www.wowhead.com/wotlk/spell=50182/aura-of-arcane-haste) still missing.

**Comment by Afgann** [comment]
fixed
