### ISSUE TITLE
Valanyr bugs: tittle not showing up in tittle list and quest item for everyone in raid.

### ISSUE THREAD

**Issue by Chupankii** [gamefreedomgit/Frostmourne#2132]
Found 2 bugs.
Made a ticket in game for the (2) but nothing changed i think.

**Description:**
1- The title that i should get from obtaining valanyr is not showing up in my character info screen https://i.imgur.com/s32V1IG.png
2- When doing the last quest, "Val'anyr, Hammer of Ancient Kings", when looting the boss for the item, everyone in the raid can loot it, 1 for each person.
3- Dont know if this is a bug but valanyr ilvl is 239 here, stats are correct.

**How to reproduce:**
1- Get the achivement.
2- Complete the quest and see if someone without it can loot it too.

**How it should work:**
1- ...
2- Only the person that has the quest should see the item.

**Database links:**
1 - Title is custom from this server, i have the last patch.

2-
Quest: https://www.wowhead.com/wotlk/quest=13629/valanyr-hammer-of-ancient-kings
Item: https://www.wowhead.com/wotlk/item=45897/reforged-hammer-of-ancient-kings

**Comment by Chupankii** [comment]
There was another post for the title:
https://github.com/gamefreedomgit/Frostmourne/issues/2120

**Comment by Afgann** [comment]
fixed

**Comment by oneadanut** [comment]
For 2. the bug is still not fixed. Last night, all people could loot the quest item. @Afgann
