### ISSUE TITLE
Unable to take out items from mail on HC character

### ISSUE THREAD

**Issue by Ka-Anor** [gamefreedomgit/Frostmourne#2207]
On a HC character, I am unable to get items from mail sent by another HC character that has been deleted, I get "Internal mail database error". Lets say HC Character1 sends mail with two items attached to HC Character2. Character2 looks at mail and takes out one item without issue. Character1 is deleted. Character2 is now unable to take out the rest of the items sent by Character1 due to "Internal mail database error". 
Note: I tested this on normal (non-HC) characters aswell, and the issue is not present. Non-HC characters can retrieve mail from deleted characters normally.

How to reproduce: Have two HC characters. Have Character1 send mail with items to Character2. Have Character2 look at mail, but not take out items. Delete Character1. You are now unable to take out items sitting in mail on Character2.

How it should work: Even after a character's death and deletion, the mail a character sent prior to being deleted should be able to be opened and received normally by other characters.

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by ItsPope** [comment]
Hi, this change seems to have been applied but I am still unable to take out mail from deleted HC chars.

**Comment by Riztazz** [comment]
Hi, it was not possible to fix the issue and also cover retroactive cases, you will need to contact a GM, sorry :(
I'll forward this issue to @RadeghostWM as well via DMs

**Comment by carlosceblop** [comment]
hi, i contacted GMs via tickets ingame, and was said there was nothing they could do and that i should contact support via whitemane creating an issue, is there other way to have this issue fixed? or other way to contact GM? thanks in advance

**Comment by Riztazz** [comment]
I have forwarded this case to higher-ups as it requires their action :)

**Comment by Riztazz** [comment]
I don't want this ticket to be stall-assigned to me, i have fixed the underlying issue and re-assigning to @itsemmastone for resolution with old mails

**Comment by emirie1** [comment]
Issue is still present, or at the very least if fixed already is still affecting characters that died before any fix was implemented. I have a character that died and was deleted and remade at least a week ago and a mail from that character on my HC bank alt that I still get the "internal mail database error" on when trying to withdraw the item that was sent.

![image](https://github.com/user-attachments/assets/cbdf56e1-efbe-494d-b644-4a99b8419c02)

**Comment by Riztazz** [comment]
Like i've said many times before, this could not be fixed retroactively, because characters were already deleted. All cases to be handled by itsemmastone where appropriate
