### ISSUE TITLE
The Lost Mistwhisper Treasure quest bug

### ISSUE THREAD

**Issue by Hasan-Smajlovic** [gamefreedomgit/Frostmourne#2246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Looting quest item (treasure) and killing warlord and it is saying "quest complete", even on quest log it says "completed" but when players to go quest giver it is still white/grey question mark. 

**How to reproduce:**
Looting quest item (treasure) and killing warlord should result in quest completion and be able to turn in to quest giver if it says "completed"

**How it should work:**
Looting quest item (treasure) and killing warlord should result in quest completion and be able to turn in to quest giver if it says "completed"

**Database links:**
https://www.youtube.com/watch?v=P8jddhyBo84
https://www.wowhead.com/wotlk/quest=12575/the-lost-mistwhisper-treasure

**Comment by Riztazz** [comment]
Are you sure you were not in raid?

**Comment by Hasan-Smajlovic** [comment]
Not in raid. Not in party.

**Comment by Riztazz** [comment]
I'm gonna push a fix and let you know when it's live on a server, can you test then? I have an idea what might have been causing an issue but can't reproduce it sadly

**Comment by Hasan-Smajlovic** [comment]
I will let you know as soon as I test it since today I have many chores.
Will probably do it in the evening.

**Comment by Riztazz** [comment]
Sure, i'll let you know when it's on a server

**Comment by Riztazz** [comment]
Realm should be updated in +- an hour, so feel free to test in the evening and let me know :) Hopefully it works now

**Comment by Hasan-Smajlovic** [comment]
Still does not work. Now it can not be looted. Someone made a ticket for it
as well. I also tried and it is not targetable. https://imgur.com/a/Gyc4kQM

sri, 6. stu 2024. u 10:42 Riztazz ***@***.***> napisao je:

**Comment by Riztazz** [comment]
How is that even possible :D I've completed that quest like 6 times while testing, i'll debug further:P

**Comment by Hasan-Smajlovic** [comment]
It also now spawns the quest "boss" like 1929299292 times  xd

**Comment by Riztazz** [comment]
Yeah, it's complete opposite of what's happening on my local server. I've uploaded a database from production server to see what's up

**Comment by Riztazz** [comment]
What did you do to spawn him multiple times? Does it spawn on gameobject use or when you arrive there?

**Comment by Hasan-Smajlovic** [comment]
GM Kryndor was also online when checking out this player while it was doing
this quest. I just tried to redo it and got the same kind of bugs as
Kryndor told me that player had. So maybe you can message him on discord
for more info?

**Comment by Riztazz** [comment]
Ok, now it should be fixed hopefully ;p not sure when realm will be updated

**Comment by bigchipbag** [comment]
It is still not working. The orb was not interactable at all, with or without the pet. 
The guy still spawns correctly, I got him twice the first time I tried but then after that it was only once.

**Comment by Riztazz** [comment]
Realm has been updated, it can be tested now
