### ISSUE TITLE
[Warlock] - Succubus -> Lesser Invisibility BUGGED

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#261]
**Description:**

Succubus' Lesser Invisibility spell is completely bugged. Whenever the warlock is taking damage, and has Soul Link, it should remove and prevent the lesser invisibility spell to be used from the pet, since both of them would enter in combat mode.

Instead of this, the succubus keeps spamming lesser invisibility whenever the warlock receives damage, which causes 2 major issues:

#1 - Mana wasted on her
#2 - Prevents you from using Seduction

**How to reproduce:**

Activate the auto Lesser Invisibility so the Succubus is free to reactivate it whenever she doesn't receive any damage, and is out of combat.

**How it should work:**

If the Warlock got a Soul Link on him, it would share the damage to the succubus. Therefore, the Lesser Invisibility would fade from the succubus, she would automatically enter in combat, and she won't be able to re-use that spell until both warlock and her are out of combat again.

**Database links:**

https://wotlk.evowow.com/?spell=7870

**Comment by Afgann** [comment]
fixed

**Comment by Naturlish** [comment]
> fixed

Sorry Afgann, but it's still not fixed.

Evidence:

https://github.com/gamefreedomgit/Frostmourne/assets/54108446/29590de1-f65d-4ffe-ba0f-4b42b73212f2
