### ISSUE TITLE
Some items bought for Echoes of the Crusade aren't refundable for 2h period

### ISSUE THREAD

**Issue by szwagierro** [gamefreedomgit/Frostmourne#2672]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** As stated in the title, some of the items bought from Echo of the Crusade Vendor are still not refundable for 2h as they should be, in my case it's Lurid Manifestation

**How to reproduce:** Buy the item and see no blue text saying "you can refund this item..." and so on, selling it to vendor would give you gold instead of Echoes back

**How it should work:** Items should be refundable for 2 hours period after buying them. You should strongly consider checking every item available from this vendor since it's a reocurring problem.

**Database links:** https://www.wowhead.com/wotlk/item=47489/lurid-manifestation

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by szwagierro** [comment]
> Fixed, I will close this issue once the fix comes live.

Is there any way I could still get a refund for it? Who should I talk to?

**Comment by scrublama** [comment]
Today Wednesday server update
"The fixes above have been applied to the Production server and are now live. "

But my undead paladin bought Juggernaut's Vtiality 47451 and it was not refundable
