### ISSUE TITLE
{dungeon boss} Hadronox boss isnt working

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#541]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hadronox is dying , respawning and reseting without any triggers or anything 

**How to reproduce:**
reach second boss in  Azjol Nerub

**How it should work:**
boss should climb up after killing couple of adds

**Database links:**
https://www.wowhead.com/wotlk/npc=28921/hadronox
**i have a recorded video if needed **

**Comment by Afgann** [comment]
fixed

**Comment by Aeradel** [comment]
> fixed

not fixed - this issue persists.

the fight relies on the players killing the first three elites so that hadronox doesn't heal nonstop, but the boss will occasionally either heal to full constantly or just teleport to the bottom and die

i can occasionally fix it, but there have been multiple instances where i can't. 

i don't know if there's a combat stop issue going on - but combat dropping seems to be the trigger - just a guess though.

**Comment by WhitemaneIsa** [comment]
@Afgann
