### ISSUE TITLE
[SHAMAN - Elemental/Enhancement] Fire Elemental Targeting Bug

### ISSUE THREAD

**Issue by gmforghieri** [gamefreedomgit/Frostmourne#56]
**Description:**
Fire Elemental targeting logic is bugged and it's not focusing on the player targer or nearest/proximity target compared to totem placement but going for random targets further away.

Due to this weird targeting of the fire elemental it can even be a burden on the raid group/player to have it summoned even though it's the biggest DPS CD of the shaman class. 

An option could be to have the fire elemental always target the target of the player instead of randomly attacking adds during a boss fight (eg: Faerlina, Razovious). An alternative option would be to have the fire elemental follow the /petattack command for instance. 

Currently on Warmane the fire elemental follows /petattack when the feral spirits(wolves) are summoned which is somewhat better because at least there is a brief period where the player can make sure that the elemental is attacking the right target instead of wandering off.

Thanks for the consideration.

**How to reproduce:**
Summon Fire elemental in a boss fights where there are adds and see the elemental go for the adds instead of the closest (boss) target attacked by the player or closest target to the totem placement.

Screenshots from PTR test run from Local Gas Station/Nickzed was wrong guild from 12-02-2024
https://www.twitch.tv/videos/2060871465t
![fireele1](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/0199f8d4-c296-4a56-b517-a8b1974a4dad)
![fireele2](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/029e44bb-a71a-4869-9008-063ecdaee651)
![fireele3](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/327c8bd5-b566-4290-8699-83f5828beb24)

**How it should work:**
Fire elemental should attack the boss/closest target to the totem placement.

https://www.youtube.com/watch?v=yrK9r7ivRWU&t=800s
https://www.youtube.com/watch?v=yrK9r7ivRWU&t=5820s
https://www.youtube.com/watch?v=yrK9r7ivRWU&t=8080s

**Database links:**
N/A

**Comment by Manpower99** [comment]
Afaik Fire Elemental Totem attack prioritizes whatever target that has flame shock from you
and Earth Elemental Totem prios your earth shock target.
its aggro range wasn't big so if you did neither it had to be summoned close to its target or it goes idle
atleast this is how it worked on original cataclysm but warmane works different and it works with petattack so not sure anymore.

**Comment by gmforghieri** [comment]
Unfortunately, it has nothing to do with flame shock in WotLK, there is not a single mention in any article about this and it also haven't been my experience playing this game for years on multiple servers.

Furthermore, if you check the open-source trinity core which Whitemane is most likely based on you can see that flame shock has nothing to do with targeting. Might be a thing on Cataclysm, no clue about that, since I never played/researched the mechanics or core of Cataclysm.

If you played the game/tested this server, it would have been apparent that flame shock has nothing to do with target selection since on pretty much any fight where there are adds (Faerlina, Razovious, KT) you always have flame shock on the target but not on the adds and it still went for the adds. I even placed the totem within 1-2 yards from the boss whereas the adds were 10+ yards away and it went on the adds.

Thanks for the input though having flame shock on the target could also be a potential implementation for target priority.

**Comment by gmforghieri** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/92ca025b-e476-4634-b290-3f19c3113cd2)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/bea837b8-5f3d-46c1-bfc4-0a295579875a)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/8a255d49-bfd4-4fee-91fc-213e761b1789)

**Comment by gforghieri** [comment]
Due to this bug, the Fire elemental (biggest dps cd of dps shamans) is completely useless in fights with more than 1 target.

It starts going for targets that are rooted and shouldnt be broken from root like at Faerlina, goes for adds on KT which are being kited, goes for adds on Instructor, goes for Zombies on Gluth.

This is happening even though the shaman is attacking the boss in all cases, and summons it right next to the boss.

Thank you.

**Comment by Afgann** [comment]
fixed

**Comment by gmforghieri** [comment]
@Afgann 

Could you please double check. The bug report is marked as fixed on github on Thursday, 22nd of Feb, but there was no changelog entry on discord recorded about this and also, there was a raid on Friday, 23rd of February and the fix was not applied.

**Comment by gforghieri** [comment]
Raided full t7 yesterday on PTR, its not fixed

@Afgann , @UltraNix , @RadeghostWM
