### ISSUE TITLE
improved 'Blizzard' spell on mage no longer slowing enemies after server restart 06/04/24 

### ISSUE THREAD

**Issue by Gnoknor** [gamefreedomgit/Frostmourne#623]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
AOE farming up until the restart and upon logging back in the mobs are no longer slowed by Blizzard.

**How to reproduce:**
Cast blizzard and watch the mobs run at you full speed.

**How it should work:**
They should be slowed.

**Database links:**

**Comment by ChronoWM** [comment]
Only rank 8 blizzard is not applying the slow, the rest seems to be working.

**Comment by Afgann** [comment]
fixed

**Comment by Gnoknor** [comment]
Rank 8 blizzard still does not work despite re opening the game.- LeanderDen 5. jun. 2024 kl. 20.31 skrev Afgann ***@***.***>:﻿
fixed

**Comment by Gnoknor** [comment]
I just tried it again. It still does not work.
